name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Copy files
      uses: canastro/copy-action@0.0.2
      with:
        source: /home/runner/work/Zeleris.NET/Zeleris.NET/NZeleris.UnitTests/XmlExamples/
        target: /home/runner/work/Zeleris.NET/Zeleris.NET/NZeleris.UnitTests/XmlExamples/
    - name: Test
      env: 
        ZelerisClientId: ${{ secrets.ZELERISAPIPASSWORD }}
        ZelerisAPIUser: ${{ secrets.ZELERISAPIUSER }}
        ZelerisAPIPassword: ${{ secrets.ZELERISAPIPASSWORD }}
      run: dotnet test --no-build --verbosity normal
